// --- DATA SETS (COMPLETE & VERIFIED) ---
const animalData = [
    { name: "Aardvark", dlc: "Base Game", continent: "Africa", biome: "Grassland", space: 220, water: 0, climbing: 0, tempMin: 18, tempMax: 40, groupSize: [1, 2], isWalkthrough: false },
    { name: "Addax", dlc: "Arid", continent: "Africa", biome: "Desert", space: 650, water: 0, climbing: 0, tempMin: 10, tempMax: 45, groupSize: [2, 10], isWalkthrough: false },
    { name: "African Buffalo", dlc: "Base Game", continent: "Africa", biome: "Grassland", space: 800, water: 120, climbing: 0, tempMin: 15, tempMax: 40, groupSize: [3, 15], isWalkthrough: false },
    { name: "African Bush Elephant", dlc: "Base Game", continent: "Africa", biome: "Grassland", space: 1500, water: 300, climbing: 0, tempMin: 18, tempMax: 40, groupSize: [1, 15], isWalkthrough: false },
    { name: "African Crested Porcupine", dlc: "Arid", continent: "Africa", biome: "Desert", space: 200, water: 0, climbing: 0, tempMin: 15, tempMax: 38, groupSize: [1, 2], isWalkthrough: false },
    { name: "African Penguin", dlc: "Africa", continent: "Africa", biome: "Temperate", space: 100, water: 200, climbing: 0, tempMin: 10, tempMax: 28, groupSize: [5, 30], isWalkthrough: false },
    { name: "African Spurred Tortoise", dlc: "Zookeepers", continent: "Africa", biome: "Desert", space: 250, water: 20, climbing: 0, tempMin: 20, tempMax: 45, groupSize: [1, 6], isWalkthrough: false },
    { name: "African Wild Dog", dlc: "Base Game", continent: "Africa", biome: "Grassland", space: 700, water: 0, climbing: 0, tempMin: 10, tempMax: 38, groupSize: [4, 12], isWalkthrough: false },
    { name: "Aldabra Giant Tortoise", dlc: "Base Game", continent: "Africa", biome: "Tropical", space: 300, water: 40, climbing: 0, tempMin: 24, tempMax: 42, groupSize: [1, 8], isWalkthrough: true },
    { name: "Alpine Goat", dlc: "Barnyard", continent: "Europe", biome: "Temperate", space: 300, water: 0, climbing: 80, tempMin: -10, tempMax: 28, groupSize: [3, 12], isWalkthrough: false },
    { name: "Alpine Ibex", dlc: "Europe", continent: "Europe", biome: "Taiga", space: 500, water: 0, climbing: 150, tempMin: -20, tempMax: 20, groupSize: [3, 10], isWalkthrough: false },
    { name: "Alpaca", dlc: "Barnyard", continent: "South America", biome: "Temperate", space: 350, water: 0, climbing: 0, tempMin: -5, tempMax: 28, groupSize: [3, 12], isWalkthrough: false },
    { name: "American Alligator", dlc: "North America", continent: "North America", biome: "Aquatic", space: 150, water: 250, climbing: 0, tempMin: 15, tempMax: 35, groupSize: [1, 5], isWalkthrough: false },
    { name: "American Beaver", dlc: "North America", continent: "North America", biome: "Aquatic", space: 100, water: 300, climbing: 0, tempMin: -10, tempMax: 25, groupSize: [2, 8], isWalkthrough: false },
    { name: "American Bison", dlc: "North America", continent: "North America", biome: "Grassland", space: 850, water: 0, climbing: 0, tempMin: -15, tempMax: 30, groupSize: [3, 12], isWalkthrough: false },
    { name: "American Standard Donkey", dlc: "Barnyard", continent: "Africa", biome: "Grassland", space: 500, water: 0, climbing: 0, tempMin: 5, tempMax: 35, groupSize: [2, 8], isWalkthrough: false },
    { name: "Amur Leopard", dlc: "Conservation", continent: "Asia", biome: "Taiga", space: 700, water: 0, climbing: 150, tempMin: -25, tempMax: 25, groupSize: [1, 1], isWalkthrough: false },
    { name: "Arctic Fox", dlc: "Arctic", continent: "North America", biome: "Tundra", space: 300, water: 0, climbing: 0, tempMin: -40, tempMax: 15, groupSize: [1, 2], isWalkthrough: false },
    { name: "Arctic Wolf", dlc: "North America", continent: "North America", biome: "Tundra", space: 800, water: 0, climbing: 0, tempMin: -40, tempMax: 15, groupSize: [4, 12], isWalkthrough: false },
    { name: "Asian Small-Clawed Otter", dlc: "Wetlands", continent: "Asia", biome: "Aquatic", space: 100, water: 100, climbing: 0, tempMin: 10, tempMax: 30, groupSize: [2, 10], isWalkthrough: false },
    { name: "Asian Water Monitor", dlc: "Tropical", continent: "Asia", biome: "Aquatic", space: 150, water: 200, climbing: 50, tempMin: 24, tempMax: 38, groupSize: [1, 1], isWalkthrough: false },
    { name: "Bactrian Camel", dlc: "Base Game", continent: "Asia", biome: "Temperate", space: 600, water: 0, climbing: 0, tempMin: -20, tempMax: 45, groupSize: [2, 8], isWalkthrough: false },
    { name: "Baird's Tapir", dlc: "Base Game", continent: "Central America", biome: "Tropical", space: 450, water: 75, climbing: 0, tempMin: 18, tempMax: 35, groupSize: [1, 2], isWalkthrough: false },
    { name: "Bengal Tiger", dlc: "Base Game", continent: "Asia", biome: "Tropical", space: 750, water: 100, climbing: 0, tempMin: 5, tempMax: 35, groupSize: [1, 1], isWalkthrough: false },
    { name: "Binturong", dlc: "Southeast Asia", continent: "Asia", biome: "Tropical", space: 250, water: 0, climbing: 150, tempMin: 22, tempMax: 35, groupSize: [1, 2], isWalkthrough: false },
    { name: "Black Rhinoceros", dlc: "Arid", continent: "Africa", biome: "Grassland", space: 900, water: 150, climbing: 0, tempMin: 15, tempMax: 40, groupSize: [1, 2], isWalkthrough: false },
    { name: "Black Wildebeest", dlc: "Base Game", continent: "Africa", biome: "Grassland", space: 650, water: 0, climbing: 0, tempMin: 12, tempMax: 40, groupSize: [5, 30], isWalkthrough: false },
    { name: "Black-and-White Ruffed Lemur", dlc: "Anniversary", continent: "Africa", biome: "Tropical", space: 150, water: 0, climbing: 120, tempMin: 20, tempMax: 35, groupSize: [2, 5], isWalkthrough: true },
    { name: "Black-tailed Prairie Dog", dlc: "North America", continent: "North America", biome: "Grassland", space: 150, water: 0, climbing: 0, tempMin: -5, tempMax: 35, groupSize: [5, 20], isWalkthrough: false },
    { name: "Blue Wildebeest", dlc: "Grasslands", continent: "Africa", biome: "Grassland", space: 650, water: 0, climbing: 0, tempMin: 12, tempMax: 40, groupSize: [5, 30], isWalkthrough: false },
    { name: "Bongo", dlc: "Base Game", continent: "Africa", biome: "Tropical", space: 550, water: 0, climbing: 0, tempMin: 18, tempMax: 32, groupSize: [2, 10], isWalkthrough: false },
    { name: "Bonobo", dlc: "Base Game", continent: "Africa", biome: "Tropical", space: 450, water: 20, climbing: 200, tempMin: 22, tempMax: 35, groupSize: [5, 15], isWalkthrough: false },
    { name: "Bornean Orangutan", dlc: "Base Game", continent: "Asia", biome: "Tropical", space: 400, water: 20, climbing: 250, tempMin: 24, tempMax: 36, groupSize: [1, 2], isWalkthrough: false },
    { name: "California Sea Lion", dlc: "North America", continent: "North America", biome: "Aquatic", space: 100, water: 350, climbing: 0, tempMin: 5, tempMax: 25, groupSize: [2, 10], isWalkthrough: false },
    { name: "Capybara", dlc: "Wetlands", continent: "South America", biome: "Aquatic", space: 200, water: 150, climbing: 0, tempMin: 18, tempMax: 35, groupSize: [4, 15], isWalkthrough: false },
    { name: "Caracal", dlc: "Grasslands", continent: "Africa", biome: "Grassland", space: 450, water: 0, climbing: 80, tempMin: 15, tempMax: 40, groupSize: [1, 2], isWalkthrough: false },
    { name: "Cheetah", dlc: "Base Game", continent: "Africa", biome: "Grassland", space: 800, water: 0, climbing: 0, tempMin: 15, tempMax: 40, groupSize: [1, 5], isWalkthrough: false },
    { name: "Chinese Pangolin", dlc: "Anniversary", continent: "Asia", biome: "Tropical", space: 150, water: 10, climbing: 80, tempMin: 22, tempMax: 35, groupSize: [1, 2], isWalkthrough: false },
    { name: "Clouded Leopard", dlc: "Southeast Asia", continent: "Asia", biome: "Tropical", space: 500, water: 20, climbing: 200, tempMin: 20, tempMax: 32, groupSize: [1, 1], isWalkthrough: false },
    { name: "Collared Peccary", dlc: "Base Game", continent: "South America", biome: "Desert", space: 300, water: 0, climbing: 0, tempMin: 10, tempMax: 35, groupSize: [2, 8], isWalkthrough: false },
    { name: "Colombian White-faced Capuchin", dlc: "South America", continent: "South America", biome: "Tropical", space: 250, water: 20, climbing: 150, tempMin: 20, tempMax: 35, groupSize: [5, 15], isWalkthrough: true },
    { name: "Common Ostrich", dlc: "Base Game", continent: "Africa", biome: "Grassland", space: 900, water: 0, climbing: 0, tempMin: 10, tempMax: 42, groupSize: [2, 7], isWalkthrough: false },
    { name: "Common Warthog", dlc: "Base Game", continent: "Africa", biome: "Grassland", space: 350, water: 30, climbing: 0, tempMin: 15, tempMax: 40, groupSize: [2, 8], isWalkthrough: false },
    { name: "Common Wombat", dlc: "Twilight", continent: "Oceania", biome: "Temperate", space: 250, water: 0, climbing: 0, tempMin: 5, tempMax: 28, groupSize: [1, 2], isWalkthrough: false },
    { name: "Coquerel's Sifaka", dlc: "Zookeepers", continent: "Africa", biome: "Tropical", space: 200, water: 0, climbing: 150, tempMin: 18, tempMax: 40, groupSize: [2, 8], isWalkthrough: false },
    { name: "Cougar", dlc: "North America", continent: "North America", biome: "Taiga", space: 700, water: 0, climbing: 100, tempMin: -15, tempMax: 30, groupSize: [1, 2], isWalkthrough: false },
    { name: "Coyote", dlc: "Base Game", continent: "North America", biome: "Grassland", space: 400, water: 0, climbing: 0, tempMin: -10, tempMax: 40, groupSize: [1, 2], isWalkthrough: false },
    { name: "Cuvier's Dwarf Caiman", dlc: "Aquatic", continent: "South America", biome: "Aquatic", space: 120, water: 200, climbing: 0, tempMin: 20, tempMax: 35, groupSize: [1, 4], isWalkthrough: false },
    { name: "Dall Sheep", dlc: "Arctic", continent: "North America", biome: "Tundra", space: 500, water: 0, climbing: 100, tempMin: -30, tempMax: 18, groupSize: [3, 10], isWalkthrough: false },
    { name: "Dama Gazelle", dlc: "Arid", continent: "Africa", biome: "Desert", space: 600, water: 0, climbing: 0, tempMin: 18, tempMax: 48, groupSize: [4, 15], isWalkthrough: false },
    { name: "Dhole", dlc: "Southeast Asia", continent: "Asia", biome: "Tropical", space: 600, water: 50, climbing: 0, tempMin: 10, tempMax: 30, groupSize: [4, 12], isWalkthrough: false },
    { name: "Dingo", dlc: "Australia", continent: "Oceania", biome: "Desert", space: 500, water: 0, climbing: 0, tempMin: 10, tempMax: 40, groupSize: [2, 8], isWalkthrough: false },
    { name: "Dromedary Camel", dlc: "Arid", continent: "Africa", biome: "Desert", space: 600, water: 0, climbing: 0, tempMin: -10, tempMax: 50, groupSize: [2, 8], isWalkthrough: false },
    { name: "Emu", dlc: "Grasslands", continent: "Oceania", biome: "Grassland", space: 700, water: 50, climbing: 0, tempMin: 5, tempMax: 35, groupSize: [2, 6], isWalkthrough: false },
    { name: "Eurasian Lynx", dlc: "Europe", continent: "Europe", biome: "Taiga", space: 600, water: 0, climbing: 80, tempMin: -25, tempMax: 22, groupSize: [1, 2], isWalkthrough: false },
    { name: "European Badger", dlc: "Europe", continent: "Europe", biome: "Temperate", space: 200, water: 0, climbing: 0, tempMin: -5, tempMax: 25, groupSize: [2, 8], isWalkthrough: false },
    { name: "European Fallow Deer", dlc: "Europe", continent: "Europe", biome: "Temperate", space: 600, water: 0, climbing: 0, tempMin: -10, tempMax: 28, groupSize: [5, 20], isWalkthrough: true },
    { name: "Fennec Fox", dlc: "Africa", continent: "Africa", biome: "Desert", space: 250, water: 0, climbing: 0, tempMin: 20, tempMax: 45, groupSize: [1, 4], isWalkthrough: false },
    { name: "Formosan Black Bear", dlc: "Base Game", continent: "Asia", biome: "Temperate", space: 700, water: 80, climbing: 50, tempMin: 5, tempMax: 30, groupSize: [1, 2], isWalkthrough: false },
    { name: "Fossa", dlc: "Tropical", continent: "Africa", biome: "Tropical", space: 400, water: 20, climbing: 180, tempMin: 18, tempMax: 32, groupSize: [1, 2], isWalkthrough: false },
    { name: "Galapagos Giant Tortoise", dlc: "Base Game", continent: "South America", biome: "Tropical", space: 300, water: 40, climbing: 0, tempMin: 22, tempMax: 38, groupSize: [1, 8], isWalkthrough: true },
    { name: "Gemsbok", dlc: "Base Game", continent: "Africa", biome: "Grassland", space: 650, water: 0, climbing: 0, tempMin: 15, tempMax: 45, groupSize: [3, 10], isWalkthrough: false },
    { name: "Gharial", dlc: "Base Game", continent: "Asia", biome: "Aquatic", space: 150, water: 350, climbing: 0, tempMin: 20, tempMax: 35, groupSize: [1, 5], isWalkthrough: false },
    { name: "Giant Anteater", dlc: "South America", continent: "South America", biome: "Grassland", space: 450, water: 0, climbing: 0, tempMin: 18, tempMax: 32, groupSize: [1, 2], isWalkthrough: false },
    { name: "Giant Otter", dlc: "Aquatic", continent: "South America", biome: "Aquatic", space: 150, water: 250, climbing: 0, tempMin: 18, tempMax: 32, groupSize: [3, 10], isWalkthrough: false },
    { name: "Giant Panda", dlc: "Base Game", continent: "Asia", biome: "Temperate", space: 700, water: 20, climbing: 100, tempMin: 0, tempMax: 25, groupSize: [1, 2], isWalkthrough: false },
    { name: "Gray Seal", dlc: "Aquatic", continent: "Europe", biome: "Aquatic", space: 100, water: 400, climbing: 0, tempMin: -5, tempMax: 20, groupSize: [2, 10], isWalkthrough: false },
    { name: "Greater Flamingo", dlc: "Base Game", continent: "Africa", biome: "Aquatic", space: 300, water: 150, climbing: 0, tempMin: 15, tempMax: 40, groupSize: [20, 100], isWalkthrough: false },
    { name: "Grizzly Bear", dlc: "Base Game", continent: "North America", biome: "Taiga", space: 800, water: 100, climbing: 0, tempMin: -10, tempMax: 22, groupSize: [1, 2], isWalkthrough: false },
    { name: "Hamadryas Baboon", dlc: "Zookeepers", continent: "Africa", biome: "Desert", space: 600, water: 20, climbing: 100, tempMin: 10, tempMax: 42, groupSize: [5, 25], isWalkthrough: false },
    { name: "Highland Cattle", dlc: "Barnyard", continent: "Europe", biome: "Temperate", space: 600, water: 0, climbing: 0, tempMin: -15, tempMax: 22, groupSize: [3, 10], isWalkthrough: false },
    { name: "Hill Radnor Sheep", dlc: "Barnyard", continent: "Europe", biome: "Temperate", space: 400, water: 0, climbing: 0, tempMin: -5, tempMax: 25, groupSize: [4, 15], isWalkthrough: false },
    { name: "Himalayan Brown Bear", dlc: "Base Game", continent: "Asia", biome: "Taiga", space: 800, water: 100, climbing: 0, tempMin: -15, tempMax: 20, groupSize: [1, 2], isWalkthrough: false },
    { name: "Hippopotamus", dlc: "Base Game", continent: "Africa", biome: "Aquatic", space: 350, water: 700, climbing: 0, tempMin: 15, tempMax: 38, groupSize: [2, 12], isWalkthrough: false },
    { name: "Indian Elephant", dlc: "Base Game", continent: "Asia", biome: "Tropical", space: 1200, water: 250, climbing: 0, tempMin: 20, tempMax: 35, groupSize: [5, 15], isWalkthrough: false },
    { name: "Indian Peafowl", dlc: "Base Game", continent: "Asia", biome: "Temperate", space: 250, water: 0, climbing: 0, tempMin: 10, tempMax: 35, groupSize: [2, 7], isWalkthrough: true },
    { name: "Indian Rhinoceros", dlc: "Base Game", continent: "Asia", biome: "Grassland", space: 800, water: 150, climbing: 0, tempMin: 15, tempMax: 35, groupSize: [1, 2], isWalkthrough: false },
    { name: "Jaguar", dlc: "South America", continent: "South America", biome: "Tropical", space: 700, water: 100, climbing: 50, tempMin: 18, tempMax: 35, groupSize: [1, 1], isWalkthrough: false },
    { name: "Japanese Macaque", dlc: "Base Game", continent: "Asia", biome: "Temperate", space: 350, water: 50, climbing: 150, tempMin: -15, tempMax: 25, groupSize: [5, 20], isWalkthrough: false },
    { name: "King Penguin", dlc: "Aquatic", continent: "Antarctica", biome: "Tundra", space: 200, water: 300, climbing: 0, tempMin: -25, tempMax: 10, groupSize: [5, 30], isWalkthrough: false },
    { name: "Kirk's Dik-Dik", dlc: "Zookeepers", continent: "Africa", biome: "Grassland", space: 200, water: 0, climbing: 0, tempMin: 15, tempMax: 40, groupSize: [1, 2], isWalkthrough: false },
    { name: "Koala", dlc: "Australia", continent: "Oceania", biome: "Temperate", space: 150, water: 0, climbing: 100, tempMin: 10, tempMax: 30, groupSize: [1, 2], isWalkthrough: false },
    { name: "Komodo Dragon", dlc: "Deluxe", continent: "Asia", biome: "Tropical", space: 500, water: 50, climbing: 0, tempMin: 25, tempMax: 40, groupSize: [1, 1], isWalkthrough: false },
    { name: "Lar Gibbon", dlc: "Tropical", continent: "Asia", biome: "Tropical", space: 300, water: 0, climbing: 200, tempMin: 22, tempMax: 35, groupSize: [2, 4], isWalkthrough: false },
    { name: "Linnaeus's Two-Toed Sloth", dlc: "Wetlands", continent: "South America", biome: "Tropical", space: 200, water: 0, climbing: 110, tempMin: 24, tempMax: 38, groupSize: [1, 2], isWalkthrough: true },
    { name: "Little Penguin", dlc: "Oceania", continent: "Oceania", biome: "Temperate", space: 80, water: 150, climbing: 0, tempMin: 10, tempMax: 25, groupSize: [5, 20], isWalkthrough: false },
    { name: "Llama", dlc: "South America", continent: "South America", biome: "Temperate", space: 400, water: 0, climbing: 0, tempMin: -5, tempMax: 30, groupSize: [3, 10], isWalkthrough: false },
    { name: "Malayan Tapir", dlc: "Southeast Asia", continent: "Asia", biome: "Tropical", space: 450, water: 75, climbing: 0, tempMin: 20, tempMax: 32, groupSize: [1, 2], isWalkthrough: false },
    { name: "Mandrill", dlc: "Base Game", continent: "Africa", biome: "Tropical", space: 500, water: 0, climbing: 150, tempMin: 20, tempMax: 32, groupSize: [5, 15], isWalkthrough: false },
    { name: "Maned Wolf", dlc: "South America", continent: "South America", biome: "Grassland", space: 550, water: 0, climbing: 0, tempMin: 15, tempMax: 35, groupSize: [1, 2], isWalkthrough: false },
    { name: "Markhor", dlc: "Zookeepers", continent: "Asia", biome: "Taiga", space: 550, water: 0, climbing: 150, tempMin: -20, tempMax: 25, groupSize: [3, 12], isWalkthrough: false },
    { name: "Meerkat", dlc: "Africa", continent: "Africa", biome: "Desert", space: 200, water: 0, climbing: 0, tempMin: 18, tempMax: 42, groupSize: [5, 15], isWalkthrough: false },
    { name: "Moose", dlc: "North America", continent: "North America", biome: "Taiga", space: 900, water: 150, climbing: 0, tempMin: -25, tempMax: 20, groupSize: [1, 3], isWalkthrough: false },
    { name: "Mouflon", dlc: "Europe", continent: "Europe", biome: "Temperate", space: 450, water: 0, climbing: 100, tempMin: -5, tempMax: 30, groupSize: [3, 12], isWalkthrough: false },
    { name: "Mute Swan", dlc: "Eurasia", continent: "Europe", biome: "Aquatic", space: 200, water: 100, climbing: 0, tempMin: -10, tempMax: 28, groupSize: [1, 2], isWalkthrough: false },
    { name: "Nile Lechwe", dlc: "Wetlands", continent: "Africa", biome: "Aquatic", space: 500, water: 100, climbing: 0, tempMin: 18, tempMax: 38, groupSize: [5, 20], isWalkthrough: false },
    { name: "Nile Monitor", dlc: "Base Game", continent: "Africa", biome: "Aquatic", space: 150, water: 200, climbing: 50, tempMin: 22, tempMax: 40, groupSize: [1, 1], isWalkthrough: false },
    { name: "Nine-banded Armadillo", dlc: "Grasslands", continent: "North America", biome: "Grassland", space: 150, water: 10, climbing: 0, tempMin: 10, tempMax: 32, groupSize: [1, 2], isWalkthrough: false },
    { name: "North Island Brown Kiwi", dlc: "Oceania", continent: "Oceania", biome: "Temperate", space: 150, water: 10, climbing: 0, tempMin: 5, tempMax: 25, groupSize: [1, 2], isWalkthrough: false },
    { name: "North Sulawesi Babirusa", dlc: "Southeast Asia", continent: "Asia", biome: "Tropical", space: 300, water: 30, climbing: 0, tempMin: 22, tempMax: 35, groupSize: [2, 5], isWalkthrough: false },
    { name: "Nyala", dlc: "Base Game", continent: "Africa", biome: "Grassland", space: 500, water: 0, climbing: 0, tempMin: 15, tempMax: 35, groupSize: [2, 8], isWalkthrough: false },
    { name: "Okapi", dlc: "Base Game", continent: "Africa", biome: "Tropical", space: 600, water: 0, climbing: 0, tempMin: 18, tempMax: 30, groupSize: [1, 2], isWalkthrough: false },
    { name: "Pallas's Cat", dlc: "Zookeepers", continent: "Asia", biome: "Taiga", space: 250, water: 0, climbing: 50, tempMin: -30, tempMax: 20, groupSize: [1, 2], isWalkthrough: false },
    { name: "Plains Zebra", dlc: "Base Game", continent: "Africa", biome: "Grassland", space: 650, water: 0, climbing: 0, tempMin: 12, tempMax: 40, groupSize: [3, 10], isWalkthrough: false },
    { name: "Platypus", dlc: "Wetlands", continent: "Oceania", biome: "Aquatic", space: 80, water: 120, climbing: 0, tempMin: 5, tempMax: 25, groupSize: [1, 2], isWalkthrough: false },
    { name: "Polar Bear", dlc: "Arctic", continent: "North America", biome: "Tundra", space: 1200, water: 400, climbing: 0, tempMin: -45, tempMax: 10, groupSize: [1, 2], isWalkthrough: false },
    { name: "Proboscis Monkey", dlc: "Southeast Asia", continent: "Asia", biome: "Tropical", space: 350, water: 50, climbing: 180, tempMin: 24, tempMax: 35, groupSize: [4, 12], isWalkthrough: false },
    { name: "Pronghorn Antelope", dlc: "Base Game", continent: "North America", biome: "Grassland", space: 650, water: 0, climbing: 0, tempMin: -5, tempMax: 35, groupSize: [3, 10], isWalkthrough: false },
    { name: "Przewalski's Horse", dlc: "Conservation", continent: "Asia", biome: "Grassland", space: 750, water: 0, climbing: 0, tempMin: -15, tempMax: 30, groupSize: [3, 10], isWalkthrough: false },
    { name: "Pygmy Hippo", dlc: "Base Game", continent: "Africa", biome: "Aquatic", space: 250, water: 400, climbing: 0, tempMin: 20, tempMax: 35, groupSize: [1, 3], isWalkthrough: false },
    { name: "Quokka", dlc: "Oceania", continent: "Oceania", biome: "Temperate", space: 200, water: 10, climbing: 0, tempMin: 12, tempMax: 30, groupSize: [3, 10], isWalkthrough: false },
    { name: "Raccoon", dlc: "Twilight", continent: "North America", biome: "Temperate", space: 200, water: 20, climbing: 100, tempMin: -10, tempMax: 30, groupSize: [1, 5], isWalkthrough: false },
    { name: "Red Deer", dlc: "Europe", continent: "Europe", biome: "Temperate", space: 700, water: 0, climbing: 0, tempMin: -15, tempMax: 28, groupSize: [2, 12], isWalkthrough: false },
    { name: "Red Fox", dlc: "Twilight", continent: "Europe", biome: "Temperate", space: 300, water: 0, climbing: 0, tempMin: -15, tempMax: 28, groupSize: [1, 2], isWalkthrough: false },
    { name: "Red Kangaroo", dlc: "Australia", continent: "Oceania", biome: "Desert", space: 800, water: 0, climbing: 0, tempMin: 10, tempMax: 45, groupSize: [3, 10], isWalkthrough: false },
    { name: "Red Panda", dlc: "Base Game", continent: "Asia", biome: "Temperate", space: 200, water: 0, climbing: 100, tempMin: 5, tempMax: 25, groupSize: [1, 2], isWalkthrough: false },
    { name: "Red River Hog", dlc: "Tropical", continent: "Africa", biome: "Tropical", space: 350, water: 40, climbing: 0, tempMin: 20, tempMax: 35, groupSize: [3, 10], isWalkthrough: false },
    { name: "Red Ruffed Lemur", dlc: "Base Game", continent: "Africa", biome: "Tropical", space: 150, water: 0, climbing: 120, tempMin: 20, tempMax: 35, groupSize: [2, 5], isWalkthrough: true },
    { name: "Red-crowned Crane", dlc: "Wetlands", continent: "Asia", biome: "Aquatic", space: 300, water: 80, climbing: 0, tempMin: -10, tempMax: 28, groupSize: [1, 2], isWalkthrough: false },
    { name: "Red-necked Wallaby", dlc: "Grasslands", continent: "Oceania", biome: "Temperate", space: 500, water: 0, climbing: 0, tempMin: 5, tempMax: 30, groupSize: [2, 8], isWalkthrough: false },
    { name: "Reindeer", dlc: "Arctic", continent: "Europe", biome: "Tundra", space: 700, water: 0, climbing: 0, tempMin: -35, tempMax: 15, groupSize: [5, 25], isWalkthrough: false },
    { name: "Reticulated Giraffe", dlc: "Base Game", continent: "Africa", biome: "Grassland", space: 1200, water: 0, climbing: 0, tempMin: 15, tempMax: 40, groupSize: [2, 8], isWalkthrough: false },
    { name: "Ring-Tailed Lemur", dlc: "Base Game", continent: "Africa", biome: "Temperate", space: 300, water: 0, climbing: 150, tempMin: 15, tempMax: 38, groupSize: [5, 15], isWalkthrough: true },
    { name: "Sable Antelope", dlc: "Base Game", continent: "Africa", biome: "Grassland", space: 700, water: 0, climbing: 0, tempMin: 15, tempMax: 38, groupSize: [5, 15], isWalkthrough: false },
    { name: "Saiga Antelope", dlc: "Eurasia", continent: "Asia", biome: "Grassland", space: 650, water: 0, climbing: 0, tempMin: -20, tempMax: 30, groupSize: [5, 20], isWalkthrough: false },
    { name: "Saltwater Crocodile", dlc: "Base Game", continent: "Oceania", biome: "Aquatic", space: 200, water: 500, climbing: 0, tempMin: 22, tempMax: 38, groupSize: [1, 1], isWalkthrough: false },
    { name: "Sand Cat", dlc: "Arid", continent: "Africa", biome: "Desert", space: 250, water: 0, climbing: 50, tempMin: 15, tempMax: 45, groupSize: [1, 2], isWalkthrough: false },
    { name: "Scimitar-horned Oryx", dlc: "Conservation", continent: "Africa", biome: "Desert", space: 700, water: 0, climbing: 0, tempMin: 18, tempMax: 48, groupSize: [4, 12], isWalkthrough: false },
    { name: "Siamang", dlc: "Conservation", continent: "Asia", biome: "Tropical", space: 350, water: 0, climbing: 200, tempMin: 22, tempMax: 35, groupSize: [2, 4], isWalkthrough: false },
    { name: "Siberian Tiger", dlc: "Base Game", continent: "Asia", biome: "Taiga", space: 800, water: 100, climbing: 0, tempMin: -20, tempMax: 25, groupSize: [1, 1], isWalkthrough: false },
    { name: "Sloth Bear", dlc: "Eurasia", continent: "Asia", biome: "Tropical", space: 500, water: 50, climbing: 80, tempMin: 15, tempMax: 35, groupSize: [1, 2], isWalkthrough: false },
    { name: "Snow Leopard", dlc: "Base Game", continent: "Asia", biome: "Taiga", space: 700, water: 0, climbing: 150, tempMin: -25, tempMax: 20, groupSize: [1, 1], isWalkthrough: false },
    { name: "Somali Wild Ass", dlc: "Arid", continent: "Africa", biome: "Desert", space: 700, water: 0, climbing: 0, tempMin: 18, tempMax: 45, groupSize: [2, 8], isWalkthrough: false },
    { name: "Southern Cassowary", dlc: "Australia", continent: "Oceania", biome: "Tropical", space: 600, water: 50, climbing: 0, tempMin: 18, tempMax: 35, groupSize: [1, 2], isWalkthrough: false },
    { name: "Southern White Rhino", dlc: "Africa", continent: "Africa", biome: "Grassland", space: 900, water: 150, climbing: 0, tempMin: 15, tempMax: 40, groupSize: [2, 5], isWalkthrough: false },
    { name: "Spectacled Bear", dlc: "Zookeepers", continent: "South America", biome: "Tropical", space: 650, water: 50, climbing: 120, tempMin: 10, tempMax: 30, groupSize: [1, 2], isWalkthrough: false },
    { name: "Spectacled Caiman", dlc: "Wetlands", continent: "South America", biome: "Aquatic", space: 120, water: 200, climbing: 0, tempMin: 20, tempMax: 35, groupSize: [1, 4], isWalkthrough: false },
    { name: "Spotted Hyena", dlc: "Base Game", continent: "Africa", biome: "Grassland", space: 600, water: 50, climbing: 0, tempMin: 10, tempMax: 40, groupSize: [2, 8], isWalkthrough: false },
    { name: "Springbok", dlc: "Base Game", continent: "Africa", biome: "Grassland", space: 550, water: 0, climbing: 0, tempMin: 12, tempMax: 42, groupSize: [5, 20], isWalkthrough: false },
    { name: "Striped Hyena", dlc: "Twilight", continent: "Africa", biome: "Desert", space: 550, water: 0, climbing: 0, tempMin: 10, tempMax: 40, groupSize: [1, 2], isWalkthrough: false },
    { name: "Striped Skunk", dlc: "Twilight", continent: "North America", biome: "Temperate", space: 180, water: 0, climbing: 0, tempMin: -5, tempMax: 30, groupSize: [1, 4], isWalkthrough: false },
    { name: "Sun Bear", dlc: "Southeast Asia", continent: "Asia", biome: "Tropical", space: 400, water: 30, climbing: 150, tempMin: 22, tempMax: 35, groupSize: [1, 2], isWalkthrough: false },
    { name: "Sussex Chicken", dlc: "Barnyard", continent: "Europe", biome: "Temperate", space: 100, water: 0, climbing: 0, tempMin: 0, tempMax: 28, groupSize: [4, 20], isWalkthrough: false },
    { name: "Takin", dlc: "Eurasia", continent: "Asia", biome: "Taiga", space: 600, water: 0, climbing: 100, tempMin: -15, tempMax: 22, groupSize: [3, 10], isWalkthrough: false },
    { name: "Tamworth Pig", dlc: "Barnyard", continent: "Europe", biome: "Temperate", space: 300, water: 30, climbing: 0, tempMin: -5, tempMax: 28, groupSize: [3, 10], isWalkthrough: false },
    { name: "Tasmanian Devil", dlc: "Oceania", continent: "Oceania", biome: "Temperate", space: 300, water: 20, climbing: 0, tempMin: 0, tempMax: 25, groupSize: [1, 2], isWalkthrough: false },
    { name: "Thomson's Gazelle", dlc: "Deluxe", continent: "Africa", biome: "Grassland", space: 600, water: 0, climbing: 0, tempMin: 15, tempMax: 40, groupSize: [5, 25], isWalkthrough: false },
    { name: "Timber Wolf", dlc: "Base Game", continent: "North America", biome: "Taiga", space: 800, water: 0, climbing: 0, tempMin: -20, tempMax: 25, groupSize: [4, 12], isWalkthrough: false },
    { name: "West African Lion", dlc: "Base Game", continent: "Africa", biome: "Grassland", space: 850, water: 50, climbing: 0, tempMin: 12, tempMax: 40, groupSize: [2, 10], isWalkthrough: false },
    { name: "Western Chimpanzee", dlc: "Base Game", continent: "Africa", biome: "Tropical", space: 500, water: 20, climbing: 250, tempMin: 20, tempMax: 32, groupSize: [5, 15], isWalkthrough: false },
    { name: "Western Lowland Gorilla", dlc: "Base Game", continent: "Africa", biome: "Tropical", space: 600, water: 0, climbing: 150, tempMin: 20, tempMax: 30, groupSize: [2, 8], isWalkthrough: false },
    { name: "Wild Boar", dlc: "Eurasia", continent: "Europe", biome: "Temperate", space: 400, water: 40, climbing: 0, tempMin: -10, tempMax: 30, groupSize: [3, 12], isWalkthrough: false },
    { name: "Wild Water Buffalo", dlc: "Wetlands", continent: "Asia", biome: "Aquatic", space: 700, water: 150, climbing: 0, tempMin: 10, tempMax: 35, groupSize: [3, 12], isWalkthrough: false },
    { name: "Wisent", dlc: "Eurasia", continent: "Europe", biome: "Temperate", space: 800, water: 0, climbing: 0, tempMin: -15, tempMax: 25, groupSize: [4, 15], isWalkthrough: false },
    { name: "Wolverine", dlc: "Eurasia", continent: "Europe", biome: "Tundra", space: 450, water: 0, climbing: 50, tempMin: -35, tempMax: 15, groupSize: [1, 1], isWalkthrough: false },
];

const exhibitAnimalData = [
    { name: "Amazonian Giant Centipede", dlc: "Base Game", tempMin: 24, tempMax: 38, humidityMin: 70, humidityMax: 90, groupSize: [1, 1], isWalkthrough: false },
    { name: "American Bullfrog", dlc: "North America", tempMin: 4, tempMax: 30, humidityMin: 60, humidityMax: 90, groupSize: [1, 4], isWalkthrough: false },
    { name: "Axolotl", dlc: "Conservation", tempMin: 16, tempMax: 18, humidityMin: 80, humidityMax: 100, groupSize: [1, 4], isWalkthrough: false },
    { name: "Boa Constrictor", dlc: "Base Game", tempMin: 24, tempMax: 38, humidityMin: 50, humidityMax: 70, groupSize: [1, 1], isWalkthrough: false },
    { name: "Brazilian Salmon Pink Tarantula", dlc: "Base Game", tempMin: 24, tempMax: 36, humidityMin: 60, humidityMax: 80, groupSize: [1, 1], isWalkthrough: false },
    { name: "Brazilian Wandering Spider", dlc: "Base Game", tempMin: 24, tempMax: 38, humidityMin: 70, humidityMax: 90, groupSize: [1, 1], isWalkthrough: false },
    { name: "Butterflies (Assorted)", dlc: "Conservation", tempMin: 20, tempMax: 35, humidityMin: 60, humidityMax: 80, groupSize: [1, 500], isWalkthrough: true, requiredPlants: ["Black-eyed Susan", "Blue Porterweed", "Buddleja", "Common Lantana", "Egyptian Starcluster", "Ixora", "Mexican Sunflower", "Pincushion Flower", "Purpletop Vervain"] },
    { name: "Common Death Adder", dlc: "Australia", tempMin: 24, tempMax: 38, humidityMin: 20, humidityMax: 40, groupSize: [1, 2], isWalkthrough: false },
    { name: "Danube Crested Newt", dlc: "Wetlands", tempMin: 4, tempMax: 24, humidityMin: 70, humidityMax: 90, groupSize: [1, 4], isWalkthrough: false },
    { name: "Diamondback Terrapin", dlc: "Aquatic", tempMin: 15, tempMax: 30, humidityMin: 40, humidityMax: 70, groupSize: [1, 5], isWalkthrough: false },
    { name: "Dung Beetle", dlc: "Africa", tempMin: 20, tempMax: 40, humidityMin: 10, humidityMax: 30, groupSize: [1, 200], isWalkthrough: false },
    { name: "Eastern Brown Snake", dlc: "Base Game", tempMin: 24, tempMax: 40, humidityMin: 20, humidityMax: 40, groupSize: [1, 1], isWalkthrough: false },
    { name: "Egyptian Fruit Bat", dlc: "Twilight", tempMin: 20, tempMax: 40, humidityMin: 40, humidityMax: 60, groupSize: [20, 200], isWalkthrough: true },
    { name: "Emerald Tree Boa", dlc: "Base Game", tempMin: 24, tempMax: 32, humidityMin: 70, humidityMax: 90, groupSize: [1, 2], isWalkthrough: false },
    { name: "European Fire Salamander", dlc: "Europe", tempMin: 8, tempMax: 20, humidityMin: 70, humidityMax: 90, groupSize: [1, 4], isWalkthrough: false },
    { name: "Gaboon Viper", dlc: "Base Game", tempMin: 22, tempMax: 32, humidityMin: 70, humidityMax: 90, groupSize: [1, 1], isWalkthrough: false },
    { name: "Gila Monster", dlc: "Base Game", tempMin: 22, tempMax: 38, humidityMin: 0, humidityMax: 20, groupSize: [1, 2], isWalkthrough: false },
    { name: "Giant Burrowing Cockroach", dlc: "Base Game", tempMin: 22, tempMax: 28, humidityMin: 60, humidityMax: 80, groupSize: [1, 20], isWalkthrough: false },
    { name: "Giant Desert Hairy Scorpion", dlc: "Base Game", tempMin: 24, tempMax: 38, humidityMin: 0, humidityMax: 20, groupSize: [1, 1], isWalkthrough: false },
    { name: "Giant Forest Scorpion", dlc: "Anniversary", tempMin: 24, tempMax: 30, humidityMin: 70, humidityMax: 80, groupSize: [1, 1], isWalkthrough: false },
    { name: "Giant Leaf Insect", dlc: "Southeast Asia", tempMin: 22, tempMax: 28, humidityMin: 70, humidityMax: 90, groupSize: [1, 5], isWalkthrough: false },
    { name: "Giant Malaysian Leaf Insect", dlc: "Anniversary", tempMin: 22, tempMax: 28, humidityMin: 70, humidityMax: 90, groupSize: [1, 5], isWalkthrough: false },
    { name: "Giant Tiger Land Snail", dlc: "Base Game", tempMin: 20, tempMax: 28, humidityMin: 70, humidityMax: 90, groupSize: [1, 5], isWalkthrough: false },
    { name: "Goliath Birdeater", dlc: "Base Game", tempMin: 24, tempMax: 36, humidityMin: 70, humidityMax: 90, groupSize: [1, 1], isWalkthrough: false },
    { name: "Goliath Frog", dlc: "Base Game", tempMin: 22, tempMax: 28, humidityMin: 80, humidityMax: 100, groupSize: [1, 1], isWalkthrough: false },
    { name: "Golden Poison Frog", dlc: "South America", tempMin: 22, tempMax: 28, humidityMin: 80, humidityMax: 100, groupSize: [1, 4], isWalkthrough: false },
    { name: "Green Iguana", dlc: "Base Game", tempMin: 26, tempMax: 42, humidityMin: 70, humidityMax: 90, groupSize: [1, 2], isWalkthrough: false },
    { name: "Lehmann's Poison Frog", dlc: "Base Game", tempMin: 22, tempMax: 28, humidityMin: 80, humidityMax: 100, groupSize: [1, 4], isWalkthrough: false },
    { name: "Lesser Antillean Iguana", dlc: "Base Game", tempMin: 26, tempMax: 42, humidityMin: 70, humidityMax: 90, groupSize: [1, 2], isWalkthrough: false },
    { name: "Mexican Redknee Tarantula", dlc: "Anniversary", tempMin: 22, tempMax: 28, humidityMin: 60, humidityMax: 70, groupSize: [1, 1], isWalkthrough: false },
    { name: "Puff Adder", dlc: "Base Game", tempMin: 24, tempMax: 40, humidityMin: 20, humidityMax: 40, groupSize: [1, 1], isWalkthrough: false },
    { name: "Red-Eyed Tree Frog", dlc: "South America", tempMin: 24, tempMax: 32, humidityMin: 80, humidityMax: 100, groupSize: [1, 8], isWalkthrough: false },
    { name: "Sacred Scarab Beetle", dlc: "Base Game", tempMin: 20, tempMax: 40, humidityMin: 10, humidityMax: 30, groupSize: [1, 200], isWalkthrough: false },
    { name: "Titan Beetle", dlc: "Base Game", tempMin: 24, tempMax: 32, humidityMin: 70, humidityMax: 90, groupSize: [1, 4], isWalkthrough: false },
    { name: "Western Diamondback Rattlesnake", dlc: "Base Game", tempMin: 24, tempMax: 40, humidityMin: 20, humidityMax: 40, groupSize: [1, 1], isWalkthrough: false },
    { name: "Yellow Anaconda", dlc: "Base Game", tempMin: 24, tempMax: 36, humidityMin: 60, humidityMax: 80, groupSize: [1, 1], isWalkthrough: false },
];

const compatibilityMap = {
    "Aardvark": ["African Buffalo", "African Bush Elephant", "African Spurred Tortoise", "Aldabra Giant Tortoise", "Black Wildebeest", "Black-and-White Ruffed Lemur", "Blue Wildebeest", "Bongo", "Bonobo", "Common Ostrich", "Common Warthog", "Coquerel's Sifaka", "Greater Flamingo", "Hamadryas Baboon", "Hippopotamus", "Kirk's Dik-Dik", "Mandrill", "Meerkat", "Nile Lechwe", "Nyala", "Okapi", "Plains Zebra", "Pygmy Hippo", "Red River Hog", "Red Ruffed Lemur", "Reticulated Giraffe", "Ring-Tailed Lemur", "Sable Antelope", "Southern White Rhino", "Springbok", "Thomson's Gazelle", "Western Lowland Gorilla"],
    "Addax": ["African Crested Porcupine", "African Spurred Tortoise", "Dama Gazelle", "Dromedary Camel", "Fennec Fox", "Gemsbok", "Hamadryas Baboon", "Meerkat", "Sand Cat", "Scimitar-horned Oryx", "Somali Wild Ass"],
    "African Buffalo": ["Aardvark", "African Bush Elephant", "Black Wildebeest", "Blue Wildebeest", "Common Ostrich", "Common Warthog", "Gemsbok", "Nyala", "Plains Zebra", "Reticulated Giraffe", "Sable Antelope", "Southern White Rhino", "Springbok", "Thomson's Gazelle"],
    "African Bush Elephant": ["Aardvark", "African Buffalo", "Black Wildebeest", "Blue Wildebeest", "Common Ostrich", "Common Warthog", "Gemsbok", "Nyala", "Plains Zebra", "Reticulated Giraffe", "Sable Antelope", "Southern White Rhino", "Springbok", "Thomson's Gazelle"],
    "African Crested Porcupine": ["Addax", "Dama Gazelle", "Dromedary Camel", "Fennec Fox", "Meerkat", "Sand Cat", "Scimitar-horned Oryx"],
    "African Spurred Tortoise": ["Aardvark", "Addax", "Dama Gazelle", "Dromedary Camel", "Fennec Fox", "Meerkat", "Sand Cat", "Scimitar-horned Oryx"],
    "Aldabra Giant Tortoise": ["Aardvark", "Black-and-White Ruffed Lemur", "Coquerel's Sifaka", "Galapagos Giant Tortoise", "Red Ruffed Lemur", "Ring-Tailed Lemur"],
    "Alpaca": ["American Standard Donkey", "Capybara", "Giant Anteater", "Greater Rhea", "Hill Radnor Sheep", "Llama", "Sussex Chicken", "Tamworth Pig"],
    "Alpine Goat": ["Alpine Ibex", "European Fallow Deer", "Highland Cattle", "Hill Radnor Sheep", "Mouflon", "Red Deer", "Sussex Chicken", "Tamworth Pig", "Wild Boar"],
    "Alpine Ibex": ["Alpine Goat", "Dall Sheep", "European Badger", "European Fallow Deer", "Markhor", "Mouflon", "Red Deer", "Reindeer", "Takin", "Wild Boar"],
    "American Bison": ["Black-tailed Prairie Dog", "Coyote", "Pronghorn Antelope"],
    "American Standard Donkey": ["Alpaca", "Gemsbok", "Highland Cattle", "Hill Radnor Sheep", "Llama", "Nyala", "Plains Zebra", "Sable Antelope", "Somali Wild Ass", "Southern White Rhino", "Springbok", "Sussex Chicken", "Tamworth Pig", "Thomson's Gazelle"],
    "Bactrian Camel": ["Przewalski's Horse", "Saiga Antelope"],
    "Baird's Tapir": ["Capybara", "Collared Peccary", "Colombian White-faced Capuchin", "Giant Anteater", "Linnaeus's Two-Toed Sloth"],
    "Black Wildebeest": ["Aardvark", "African Buffalo", "African Bush Elephant", "Blue Wildebeest", "Common Ostrich", "Common Warthog", "Gemsbok", "Nyala", "Plains Zebra", "Reticulated Giraffe", "Sable Antelope", "Southern White Rhino", "Springbok", "Thomson's Gazelle"],
    "Black-and-White Ruffed Lemur": ["Aardvark", "Aldabra Giant Tortoise", "Red Ruffed Lemur", "Ring-Tailed Lemur"],
    "Black-tailed Prairie Dog": ["American Bison", "Pronghorn Antelope"],
    "Blue Wildebeest": ["Aardvark", "African Buffalo", "African Bush Elephant", "Black Wildebeest", "Common Ostrich", "Common Warthog", "Gemsbok", "Nyala", "Plains Zebra", "Reticulated Giraffe", "Sable Antelope", "Southern White Rhino", "Springbok", "Thomson's Gazelle"],
    "Bongo": ["Aardvark", "Bonobo", "Mandrill", "Okapi", "Pygmy Hippo", "Red River Hog", "Western Chimpanzee", "Western Lowland Gorilla"],
    "Bonobo": ["Aardvark", "Bongo", "Okapi", "Pygmy Hippo", "Western Chimpanzee", "Western Lowland Gorilla"],
    "Bornean Orangutan": ["Lar Gibbon", "Malayan Tapir", "Siamang", "Wild Water Buffalo"],
    "Capybara": ["Alpaca", "Baird's Tapir", "Collared Peccary", "Giant Anteater", "Greater Rhea", "Llama"],
    "Chinese Pangolin": ["Binturong", "Red Panda", "Wild Water Buffalo"],
    "Clouded Leopard": ["Binturong", "Malayan Tapir"],
    "Collared Peccary": ["Baird's Tapir", "Capybara", "Cuvier's Dwarf Caiman", "Giant Anteater", "Spectacled Caiman"],
    "Colombian White-faced Capuchin": ["Baird's Tapir", "Giant Anteater", "Linnaeus's Two-Toed Sloth"],
    "Common Ostrich": ["Aardvark", "African Buffalo", "African Bush Elephant", "Black Wildebeest", "Blue Wildebeest", "Common Warthog", "Gemsbok", "Nyala", "Plains Zebra", "Reticulated Giraffe", "Sable Antelope", "Southern White Rhino", "Springbok", "Thomson's Gazelle"],
    "Common Warthog": ["Aardvark", "African Buffalo", "African Bush Elephant", "Black Wildebeest", "Blue Wildebeest", "Common Ostrich", "Gemsbok", "Nyala", "Plains Zebra", "Reticulated Giraffe", "Sable Antelope", "Southern White Rhino", "Springbok", "Thomson's Gazelle"],
    "Coquerel's Sifaka": ["Aardvark", "Aldabra Giant Tortoise"],
    "Coyote": ["American Bison"],
    "Cuvier's Dwarf Caiman": ["Collared Peccary", "Giant Otter", "Spectacled Caiman"],
    "Dall Sheep": ["Alpine Ibex", "Markhor", "Reindeer", "Takin"],
    "Dama Gazelle": ["Addax", "African Crested Porcupine", "African Spurred Tortoise", "Dromedary Camel", "Fennec Fox", "Meerkat", "Sand Cat", "Scimitar-horned Oryx"],
    "Dromedary Camel": ["Addax", "African Crested Porcupine", "African Spurred Tortoise", "Dama Gazelle", "Fennec Fox", "Meerkat", "Sand Cat", "Scimitar-horned Oryx"],
    "Emu": ["Red Kangaroo", "Red-necked Wallaby", "Southern Cassowary"],
    "European Badger": ["Alpine Ibex", "European Fallow Deer", "Mouflon", "Red Deer", "Wild Boar"],
    "European Fallow Deer": ["Alpine Goat", "Alpine Ibex", "European Badger", "Highland Cattle", "Hill Radnor Sheep", "Mouflon", "Red Deer", "Sussex Chicken", "Tamworth Pig", "Wild Boar"],
    "Fennec Fox": ["Addax", "African Crested Porcupine", "African Spurred Tortoise", "Dama Gazelle", "Dromedary Camel", "Meerkat", "Sand Cat", "Scimitar-horned Oryx"],
    "Galapagos Giant Tortoise": ["Aldabra Giant Tortoise"],
    "Gemsbok": ["Addax", "African Buffalo", "African Bush Elephant", "American Standard Donkey", "Black Wildebeest", "Blue Wildebeest", "Common Ostrich", "Common Warthog", "Nyala", "Plains Zebra", "Reticulated Giraffe", "Sable Antelope", "Southern White Rhino", "Springbok", "Thomson's Gazelle"],
    "Gharial": ["Greater Flamingo", "Indian Elephant", "Indian Peafowl", "Indian Rhinoceros", "Wild Boar", "Wild Water Buffalo"],
    "Giant Anteater": ["Alpaca", "Baird's Tapir", "Capybara", "Collared Peccary", "Colombian White-faced Capuchin", "Greater Rhea", "Linnaeus's Two-Toed Sloth", "Llama"],
    "Giant Otter": ["Cuvier's Dwarf Caiman", "Spectacled Caiman"],
    "Giant Panda": ["Red-crowned Crane", "Wild Boar"],
    "Greater Flamingo": ["Aardvark", "Gharial", "Indian Elephant", "Indian Peafowl", "Indian Rhinoceros", "Wild Boar", "Wild Water Buffalo"],
    "Greater Rhea": ["Alpaca", "Capybara", "Giant Anteater", "Llama"],
    "Hamadryas Baboon": ["Aardvark", "Addax"],
    "Highland Cattle": ["Alpine Goat", "American Standard Donkey", "European Fallow Deer", "Hill Radnor Sheep", "Mouflon", "Red Deer", "Sussex Chicken", "Tamworth Pig", "Wild Boar"],
    "Hill Radnor Sheep": ["Alpaca", "Alpine Goat", "American Standard Donkey", "European Fallow Deer", "Highland Cattle", "Llama", "Mouflon", "Red Deer", "Sussex Chicken", "Tamworth Pig", "Wild Boar"],
    "Hippopotamus": ["Aardvark"],
    "Indian Elephant": ["Gharial", "Greater Flamingo", "Indian Peafowl", "Indian Rhinoceros", "Malayan Tapir", "Wild Boar", "Wild Water Buffalo"],
    "Indian Peafowl": ["Gharial", "Greater Flamingo", "Indian Elephant", "Indian Rhinoceros", "Malayan Tapir", "Wild Water Buffalo"],
    "Indian Rhinoceros": ["Gharial", "Greater Flamingo", "Indian Elephant", "Indian Peafowl", "Malayan Tapir", "Wild Water Buffalo"],
    "Japanese Macaque": ["Red-crowned Crane", "Wild Boar"],
    "Kirk's Dik-Dik": ["Aardvark"],
    "Lar Gibbon": ["Bornean Orangutan", "Malayan Tapir", "Siamang", "Wild Water Buffalo"],
    "Linnaeus's Two-Toed Sloth": ["Baird's Tapir", "Colombian White-faced Capuchin", "Giant Anteater"],
    "Llama": ["Alpaca", "American Standard Donkey", "Capybara", "Giant Anteater", "Greater Rhea", "Hill Radnor Sheep", "Sussex Chicken", "Tamworth Pig"],
    "Malayan Tapir": ["Bornean Orangutan", "Clouded Leopard", "Indian Elephant", "Indian Peafowl", "Indian Rhinoceros", "Lar Gibbon", "Proboscis Monkey", "Siamang", "Wild Boar"],
    "Mandrill": ["Aardvark", "Bongo", "Okapi", "Pygmy Hippo", "Red River Hog", "Western Lowland Gorilla"],
    "Markhor": ["Alpine Ibex", "Dall Sheep", "Takin", "Wild Boar"],
    "Meerkat": ["Aardvark", "Addax", "African Crested Porcupine", "African Spurred Tortoise", "Dama Gazelle", "Dromedary Camel", "Fennec Fox", "Sand Cat", "Scimitar-horned Oryx"],
    "Mouflon": ["Alpine Goat", "Alpine Ibex", "European Badger", "European Fallow Deer", "Highland Cattle", "Hill Radnor Sheep", "Red Deer", "Wild Boar"],
    "Nile Lechwe": ["Aardvark"],
    "North Sulawesi Babirusa": ["Wild Boar", "Wild Water Buffalo"],
    "Nyala": ["Aardvark", "African Buffalo", "African Bush Elephant", "American Standard Donkey", "Black Wildebeest", "Blue Wildebeest", "Common Ostrich", "Common Warthog", "Gemsbok", "Plains Zebra", "Reticulated Giraffe", "Sable Antelope", "Southern White Rhino", "Springbok", "Thomson's Gazelle"],
    "Okapi": ["Aardvark", "Bongo", "Bonobo", "Mandrill", "Pygmy Hippo", "Red River Hog", "Western Chimpanzee", "Western Lowland Gorilla"],
    "Plains Zebra": ["Aardvark", "African Buffalo", "African Bush Elephant", "American Standard Donkey", "Black Wildebeest", "Blue Wildebeest", "Common Ostrich", "Common Warthog", "Gemsbok", "Nyala", "Reticulated Giraffe", "Sable Antelope", "Southern White Rhino", "Springbok", "Thomson's Gazelle"],
    "Pronghorn Antelope": ["American Bison", "Black-tailed Prairie Dog"],
    "Przewalski's Horse": ["Bactrian Camel", "Saiga Antelope"],
    "Pygmy Hippo": ["Aardvark", "Bongo", "Bonobo", "Mandrill", "Okapi", "Red River Hog", "Western Chimpanzee", "Western Lowland Gorilla"],
    "Red Deer": ["Alpine Goat", "Alpine Ibex", "European Badger", "European Fallow Deer", "Highland Cattle", "Hill Radnor Sheep", "Mouflon", "Wild Boar"],
    "Red Kangaroo": ["Emu", "Red-necked Wallaby", "Southern Cassowary"],
    "Red Panda": ["Chinese Pangolin"],
    "Red River Hog": ["Aardvark", "Bongo", "Mandrill", "Okapi", "Pygmy Hippo", "Western Lowland Gorilla"],
    "Red Ruffed Lemur": ["Aardvark", "Aldabra Giant Tortoise", "Black-and-White Ruffed Lemur", "Ring-Tailed Lemur"],
    "Red-crowned Crane": ["Giant Panda", "Japanese Macaque", "Wild Boar"],
    "Red-necked Wallaby": ["Emu", "Red Kangaroo", "Southern Cassowary"],
    "Reindeer": ["Alpine Ibex", "Dall Sheep", "Takin"],
    "Reticulated Giraffe": ["Aardvark", "African Buffalo", "African Bush Elephant", "Black Wildebeest", "Blue Wildebeest", "Common Ostrich", "Common Warthog", "Gemsbok", "Nyala", "Plains Zebra", "Sable Antelope", "Southern White Rhino", "Springbok", "Thomson's Gazelle"],
    "Ring-Tailed Lemur": ["Aardvark", "Aldabra Giant Tortoise", "Black-and-White Ruffed Lemur", "Red Ruffed Lemur"],
    "Sable Antelope": ["Aardvark", "African Buffalo", "African Bush Elephant", "American Standard Donkey", "Black Wildebeest", "Blue Wildebeest", "Common Ostrich", "Common Warthog", "Gemsbok", "Nyala", "Plains Zebra", "Reticulated Giraffe", "Southern White Rhino", "Springbok", "Thomson's Gazelle"],
    "Saiga Antelope": ["Bactrian Camel", "Przewalski's Horse"],
    "Sand Cat": ["Addax", "African Crested Porcupine", "African Spurred Tortoise", "Dama Gazelle", "Dromedary Camel", "Fennec Fox", "Meerkat", "Scimitar-horned Oryx"],
    "Scimitar-horned Oryx": ["Addax", "African Crested Porcupine", "African Spurred Tortoise", "Dama Gazelle", "Dromedary Camel", "Fennec Fox", "Meerkat", "Sand Cat"],
    "Siamang": ["Bornean Orangutan", "Lar Gibbon", "Malayan Tapir"],
    "Somali Wild Ass": ["American Standard Donkey"],
    "Southern Cassowary": ["Emu", "Red Kangaroo", "Red-necked Wallaby"],
    "Southern White Rhino": ["Aardvark", "African Buffalo", "African Bush Elephant", "American Standard Donkey", "Black Wildebeest", "Blue Wildebeest", "Common Ostrich", "Common Warthog", "Gemsbok", "Nyala", "Plains Zebra", "Reticulated Giraffe", "Sable Antelope", "Springbok", "Thomson's Gazelle"],
    "Spectacled Caiman": ["Collared Peccary", "Cuvier's Dwarf Caiman", "Giant Otter"],
    "Springbok": ["Aardvark", "African Buffalo", "African Bush Elephant", "American Standard Donkey", "Black Wildebeest", "Blue Wildebeest", "Common Ostrich", "Common Warthog", "Gemsbok", "Nyala", "Plains Zebra", "Reticulated Giraffe", "Sable Antelope", "Southern White Rhino", "Thomson's Gazelle"],
    "Sussex Chicken": ["Alpaca", "Alpine Goat", "American Standard Donkey", "European Fallow Deer", "Highland Cattle", "Hill Radnor Sheep", "Llama", "Mouflon", "Red Deer", "Tamworth Pig", "Wild Boar"],
    "Takin": ["Alpine Ibex", "Dall Sheep", "Markhor", "Reindeer", "Wild Boar"],
    "Tamworth Pig": ["Alpaca", "Alpine Goat", "American Standard Donkey", "European Fallow Deer", "Highland Cattle", "Hill Radnor Sheep", "Llama", "Mouflon", "Red Deer", "Sussex Chicken", "Wild Boar"],
    "Thomson's Gazelle": ["Aardvark", "African Buffalo", "African Bush Elephant", "American Standard Donkey", "Black Wildebeest", "Blue Wildebeest", "Common Ostrich", "Common Warthog", "Gemsbok", "Nyala", "Plains Zebra", "Reticulated Giraffe", "Sable Antelope", "Southern White Rhino", "Springbok"],
    "Western Chimpanzee": ["Bongo", "Bonobo", "Okapi", "Pygmy Hippo", "Western Lowland Gorilla"],
    "Western Lowland Gorilla": ["Aardvark", "Bongo", "Bonobo", "Mandrill", "Okapi", "Pygmy Hippo", "Red River Hog", "Western Chimpanzee"],
    "Wild Boar": ["Alpine Goat", "Alpine Ibex", "European Badger", "European Fallow Deer", "Gharial", "Giant Panda", "Greater Flamingo", "Hamadryas Baboon", "Highland Cattle", "Hill Radnor Sheep", "Indian Elephant", "Indian Peafowl", "Indian Rhinoceros", "Japanese Macaque", "Malayan Tapir", "Markhor", "Mouflon", "North Sulawesi Babirusa", "Red Deer", "Red-crowned Crane", "Sussex Chicken", "Takin", "Tamworth Pig", "Wild Water Buffalo", "Wisent"],
    "Wild Water Buffalo": ["Bornean Orangutan", "Chinese Pangolin", "Gharial", "Greater Flamingo", "Indian Elephant", "Indian Peafowl", "Lar Gibbon", "North Sulawesi Babirusa", "Wild Boar"],
    "Wisent": ["Wild Boar"]
};
